# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
    - uses: actions/checkout@v2
    - run : npm i
      shell: bash
    - run : npm ci
      shell: bash
    - run : npm run build
      shell: bash
        # Deploy to Github Pages
    - id: deploy
      name: Deploy to Github Pages
      uses: fcodelabs/react-deploy-github-pages-action@v1.0.0
      with:
          build_dir: build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
